import type { AutoDmDatabase } from "@/lib/db";
import { subHours, subMinutes } from "date-fns";

const OPENERS = [
  "Hey! Just found your page, love the content 🙌",
  "Quick question — do you offer a payment plan?",
  "Is the roadmap still available?",
  "Following up on my last message, any update?",
  "Thanks for the reply earlier!",
  "Can you tell me more about pricing?",
];

const BOT_REPLIES = [
  "Thanks for reaching out! Here's what you need 🙌",
  "Great question — let me get that info for you.",
  "Absolutely, here's the link: {{link}}",
];

/**
 * Seeds a handful of Conversations + Messages for an account, either from
 * existing Contacts (Instagram — reuses leads already generated by the
 * AutoDM funnel) or freshly created ones (Facebook).
 */
export async function seedConversationsForAccount(
  db: AutoDmDatabase,
  workspaceId: string,
  socialAccountId: string,
  platform: "INSTAGRAM" | "MESSENGER",
  contactIds: string[],
  rng: () => number,
) {
  await db.message.deleteMany({ where: { conversation: { socialAccountId } } });
  await db.conversation.deleteMany({ where: { socialAccountId } });

  const now = new Date();

  for (const contactId of contactIds) {
    const hoursAgo = rng() * 240; // spread across the last 10 days
    const lastInboundAt = subHours(now, hoursAgo);
    const opener = OPENERS[Math.floor(rng() * OPENERS.length)];

    const conversation = await db.conversation.create({
      data: {
        workspaceId,
        socialAccountId,
        contactId,
        platform,
        status: rng() < 0.15 ? "PENDING" : "OPEN",
        botPaused: rng() < 0.1,
        lastInboundAt,
        lastMessageAt: lastInboundAt,
      },
    });

    await db.message.create({
      data: {
        conversationId: conversation.id,
        direction: "INBOUND",
        senderType: "CONTACT",
        body: opener,
        sentAt: subMinutes(lastInboundAt, 2),
      },
    });

    if (rng() < 0.75) {
      const reply = BOT_REPLIES[Math.floor(rng() * BOT_REPLIES.length)];
      await db.message.create({
        data: {
          conversationId: conversation.id,
          direction: "OUTBOUND",
          senderType: "BOT",
          body: reply,
          sentAt: lastInboundAt,
        },
      });
      await db.conversation.update({
        where: { id: conversation.id },
        data: { lastMessageAt: lastInboundAt },
      });
    }
  }
}
